(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var e="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},h=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},k=h(this),l;
if("function"==typeof Object.setPrototypeOf)l=Object.setPrototypeOf;else{var m;a:{var n={a:!0},p={};try{p.__proto__=n;m=p.a;break a}catch(a){}m=!1}l=m?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=l;var r=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},t=function(a){if(r(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&r(a))return a;return null},u=function(a,b){return b!=a.getAttribute("source")?(a.setAttribute("source",b),!0):!1};var v=function(a,b){var c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d)},w=function(a,b,c){var d=function(f){a.removeEventListener(b,d);c(f)};a.addEventListener(b,d)};var x=function(a){return/^[\s\xa0]*$/.test(a)};var y={F:"alignment",G:"bgcolor",H:"disabled",I:"down-image",J:"over-image",K:"scaling",L:"up-image"},z=[],A=0,B;for(B in y)z[A++]=y[B];var C=function(){var a=HTMLElement.call(this)||this;a.i="gwd_imagebutton_"+(2147483648*Math.random()|0);a.g=null;a.o=null;a.h=!1;a.A=!1;a.s=document.createElement("gwd-image");a.m=document.createElement("gwd-image");a.j=document.createElement("gwd-image");a.u=document.createElement("gwd-page");a.v=a.B.bind(a);a.D=a.C.bind(a);a.l=!1;return a},D=HTMLElement;
C.prototype=e(D.prototype);C.prototype.constructor=C;if(q)q(C,D);else for(var E in D)if("prototype"!=E)if(Object.defineProperties){var F=Object.getOwnPropertyDescriptor(D,E);F&&Object.defineProperty(C,E,F)}else C[E]=D[E];
C.prototype.connectedCallback=function(){if(!this.l){for(var a;a=this.firstChild;)this.removeChild(a);this.g=document.createElement("div");this.g.className=this.i;this.appendChild(this.g);this.style.display="inline-block";this.style.padding=0;this.g.style.backgroundRepeat="no-repeat";this.g.style.width="100%";this.g.style.height="100%";this.l=!0;a=["bgcolor","alignment","scaling","disabled"];for(var b=0;b<a.length;b++){var c=a[b];this.attributeChangedCallback(c,null,this.getAttribute(c),null)}}this.g.addEventListener("click",
this.v,!1);this.gwdIsLoaded()||((a=t(this))?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad())};C.prototype.disconnectedCallback=function(){this.g.removeEventListener("click",this.v,!1)};
C.prototype.attributeChangedCallback=function(a,b,c){if(this.l)switch(a){case "alignment":c?this.g.style.backgroundPosition=c:this.setAttribute(a,"center");break;case "scaling":c?this.g.style.backgroundSize=c:this.setAttribute(a,"auto");break;case "up-image":G(this,this.s,c||"");break;case "over-image":G(this,this.m,c||"");break;case "down-image":G(this,this.j,c||"");break;case "disabled":this.h=this.hasAttribute("disabled")&&"false"!=this.getAttribute("disabled");H(this);this.g.style.cursor=this.h?
"default":"pointer";break;case "bgcolor":this.g.style.backgroundColor=c&&!x(c)?c:""}};var G=function(a,b,c){x(c)?H(a):(b.setAttribute("source",c),a.l&&I(a))};C.prototype.gwdIsLoaded=function(){return this.A};C.prototype.gwdLoad=function(){I(this)};
var I=function(a,b,c,d){b=b?b:a.getAttribute("up-image");c=c?c:a.getAttribute("over-image");d=d?d:a.getAttribute("down-image");var f=document.createElement("gwd-page");f.style.display="none";var g=!1;g=u(a.s,b||"")||g;g=u(a.m,c||"")||g;if(g=u(a.j,d||"")||g)f.appendChild(a.s),f.appendChild(a.m),f.appendChild(a.j),a.u=f,w(f,"attached",f.gwdLoad.bind(f)),w(f,"pageload",a.D),a.g.appendChild(a.u)};
C.prototype.C=function(a){if(a){a=a.target;a===this.u&&(this.A=!0,H(this),v("ready",this),v("imagebuttonloaded",this));var b=a.parentNode||a.parentElement;b&&b.removeChild(a)}};C.prototype.B=function(a){this.h&&a.stopPropagation()};
var H=function(a){if(a.o){var b=a.o;(b=b.ownerNode||b.owningElement||b)&&b.parentNode&&b.parentNode.removeChild(b);a.o=null}b="";var c=a.s.getAttribute("source");x(c)||(b+="."+a.i+' { background-image: url("'+c+'"); }');a.h||(c=a.m.getAttribute("source"),x(c)||(b+="."+a.i+':hover { background-image: url("'+c+'"); }'),c=a.j.getAttribute("source"),x(c)||(b+="."+a.i+':active { background-image: url("'+c+'"); }'));var d=document;c=d.getElementsByTagName("head")[0];if(!c){var f=d.getElementsByTagName("body")[0];
c=d.createElement("head");f.parentNode.insertBefore(c,f)}d=d.createElement("style");d.textContent=b;c.appendChild(d);a.o=d};C.prototype.toggleEnable=function(){(this.h=!this.h)?this.setAttribute("disabled","true"):this.removeAttribute("disabled")};C.prototype.setImages=function(a,b,c){I(this,a,b,c)};k.Object.defineProperties(C,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return z}}});customElements.define("gwd-imagebutton",C);}).call(this);
